name: butterlabs
favicon: null
layout_spectrum: 1
typography_spectrum: 0.88222
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#6b6b6c'
    - '#8ebdd7'
    - '#939394'
    - '#dddddd'
  brandStrength: 0.8125
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
