name: butterlabs
favicon: null
layout_spectrum: 0.622075712075457
typography_spectrum: 0.3402893890161067
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#6b6b6c'
    - '#8ebdd7'
    - '#939394'
    - '#dddddd'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 1
purpose: []
